name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SPM tests
      run: swift test --sanitize=thread
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['nightly-5.4-bionic', 'nightly-5.4-focal', 'nightly-5.4-centos8', 'nightly-5.4-amazonlinux2']
    
    container:
      image: swiftlang/swift:${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        swift test --enable-test-discovery --sanitize=thread
